### ISSUE TITLE
Not Installing

### ISSUE THREAD

**Issue by MrScopes** [hyurl/better-sqlite-pool#2]
I'm using `npm i better-sqlite-pool` but it still isn't installing. Tried several times.

**Comment by hyurl** [comment]
This version uses an old version of [better-sqlite](https://github.com/JoshuaWise/better-sqlite3), it might be a little trouble when installing, please try installing **node-gyp** and Visual Studio 2015 (if on Windows) first.
A PR [#1](https://github.com/hyurl/better-sqlite-pool/pull/1) has been posted several days ago suggested upgrading to **better-sqlite** 5.x instead, however it doesn't support NodeJS version that lower than 8.9.4, I have issued [#186](https://github.com/JoshuaWise/better-sqlite3/issues/186) the author of that, who said that may be supported in the future. So now I have to wait the new version published.

**Comment by hyurl** [comment]
This module now uses **better-sqlite3** version 5.2, it should fix some installation problems as claimed to be, try the new version if you'd like.
