### ISSUE TITLE
Many "statement may fall through" while installing

### ISSUE THREAD

**Issue by Angel-0** [hyurl/better-sqlite-pool#3]
## Description
While installing this package with npm, I'm getting a lot of `warning: this statement may fall through [-Wimplicit-fallthrough=]` as you can see [here](https://gist.github.com/Angel-0/eab6feedb8e45fe64c7db735ceaf3678).
I absolutely need this package as it is a depedency for Enmap.

## System information

Versions:
* NPM: `6.4.1`
* Node: `10.15.2`
* Ubuntu: `18.04`
* GCC: `7.3.0`

## Additional comments

If any other information are needed, I'll be glad to provide them.
By the way, this might not be directly related to this package, but to [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3).

**Comment by hyurl** [comment]
Yes, these errors come from **better-sqlite3** itself and only happen when using GCC 7+, I've found this post you may be interested in:
https://stackoverflow.com/questions/45129741/gcc-7-wimplicit-fallthrough-warnings-and-portable-way-to-clear-them
However, these errors don't break the installation though, the driver can still work.

**Comment by Angel-0** [comment]
It kinda breaks it as Enmap doesn't recognise the package and still sends a warning, although it is installed. 
It worked fine on my Windows 10 computer.

---

Here is the result of [`npm ls`](https://gist.github.com/Angel-0/0ed2b22719eeec1dd54feb3ca7952ca0) on Debian, and the [one](https://gist.github.com/Angel-0/c689015e3340ba8d39cc2346ebe9fbb9) on Windows.
