### ISSUE TITLE
Constructor options doesn't support 2 new options since better-sqlite3@5.0.0

### ISSUE THREAD

**Issue by ConPac** [hyurl/better-sqlite-pool#4]
There are 2 new options introduced in better-sqlite3 v5.0.0 and v5.4.0: timeout and verbose.
https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/api.md#new-databasepath-options

**Comment by hyurl** [comment]
Sorry, I've been busy lately, I just updated this package, you can run `npm update better-sqlite-pool` to update it now.

**Comment by ConPac** [comment]
Thank you very much for your fix.
