### ISSUE TITLE
Gives me error when trying to install

### ISSUE THREAD

**Issue by Protegus** [hyurl/better-sqlite-pool#5]
Here is the error: 

`
C:\Users\Kaiden\Desktop\KTG bot>npm i better-sqlite-pool

> integer@2.1.0 install C:\Users\Kaiden\Desktop\KTG bot\node_modules\integer
> node-gyp rebuild

C:\Users\Kaiden\Desktop\KTG bot\node_modules\integer>if not defined npm_config_n
ode_gyp (node "C:\Users\Kaiden\AppData\Roaming\npm\node_modules\npm\node_modules
\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuil
d )  else (node "C:\Users\Kaiden\AppData\Roaming\npm\node_modules\npm\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targ
ets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\Kai
den\Desktop\KTG bot\node_modules\integer\build\integer.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Kaiden\AppData\Roaming\npm\n
ode_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:248:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kaiden\\AppDa
ta\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild"
gyp ERR! cwd C:\Users\Kaiden\Desktop\KTG bot\node_modules\integer
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but non
e is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is insta
lled. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installe
d. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none
 is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed.
 You must install peer dependencies yourself.
npm WARN enmap@4.8.1 requires a peer of better-sqlite-pool@github:eslachance/bet
ter-sqlite-pool but none is installed. You must install peer dependencies yourse
lf.
npm WARN ktg-bot@1.0.0 No description
npm WARN ktg-bot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kaiden\AppData\Roaming\npm-cache\_logs\2019-03-31T15_14_01
_025Z-debug.log

C:\Users\Kaiden\Desktop\KTG bot>`

**Comment by VenkSociety** [comment]
Also getting the same error. `Node-gyp` is installed and so are the dependencies. @hyurl any ideas?

**Comment by hyurl** [comment]
Sorry, I cannot reproduce this error, it seems to be an error caused either by the system (Windows 7) or the compiler environment, I've tried on Windows 10 with Visual Studio 2015 and it installed fine. Anyway, try to reinstall Visual Studio with C++ builder, it not helping, then try to install Visual Studio 2017 or higher versions, if none of them helped, then you might want to upgrade your system as well.
