### ISSUE TITLE
npm install / node-gyp failure

### ISSUE THREAD

**Issue by nuxy** [hyurl/better-sqlite-pool#7]
In my case, the issue occurs in a virtualized environment (eg. _Vagrant/FreeBSD_) but there have been other reports of [similar behaviour which is likely related](https://github.com/hyurl/better-sqlite-pool/issues/5).

The [crux of the issue](https://github.com/JoshuaWise/better-sqlite3/issues/277) is due to a dependency (`integer`) used in `better-sqlite3`

**Resolution**
- Update `better-sqlite3` (>= 6.0.1).

**Comment by hyurl** [comment]
I have upgraded `better-sqlite3` to **6.0.1** and republished this module using a newer version number **0.3** in order to prevent any potential incompatibility, thanks for pointing this issue out, hope this upgrade will fix for all environments.
